steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: ARM - WIF - manual
    scriptType: pscore
    scriptLocation: inlineScript
    inlineScript: |
      az account set --subscription $(SUBSCRIPTION_ID)
      $accessToken = az account get-access-token --resource $(RESOURCE_ID) --query accessToken --output tsv
      echo "##vso[task.setvariable variable=ACCESS_TOKEN;issecret=true]$accessToken"
  displayName: Get Access Token
